- index.js
- package.json
- test/base-path.js
- test/host-header.js
As titled.
Both fixes are tested in `test/host-header.js`.
> Fixed host and pathname handling

- index.js
- test/get-with-body.js
according to https://tools.ietf.org/html/rfc2616#section-4.3. fastify ignore message body when it's a GET request. when proxy this request, we should reset the content-length to make it a valid http request discussion: https://github.com/fastify/fastify/issues/953
> reset request body when proxy get request from fastify

- .gitignore
- index.js
- test/full-querystring-rewrite-option-complex.js
fix ignore queryString when request a source contains url.search.
This is the first step to fix, potential need migrate to `queryString` function as @mcollina suggest.
> fix ignore queryString

- index.js
- test/padded-body.js
If an incoming request has a JSON-stringified body with non-zero spacing, the content length will be incorrect after parsing/stringifying it.
Since the headers are just forwarded, the content-length header will have an incorrect number of bytes, and will result in the target server either hanging when waiting for more bytes, or truncating the body if there are less bytes than specified.
This recalculates the length of the body, and sets the type as well (this should be json since it is stringifed by JSON, right?)
> Fix incorrect content-length and content-type for padded bodies

- README.md
- index.js
- test/transform-body.js
This is my attempt to allow `replyOptions` to work in `fastify-http-proxy`. The PR in question is here: https://github.com/fastify/fastify-http-proxy/pull/34
The only way that I am able to get this to work is to change the contract in `fastify-reply-from` so that `request, reply, res` are all available. If this is acceptable let me know and I will update the other reply with the appropriate test. 
Thanks again!
> Change onresponse contract to allow request, reply, and res.

- README.md
- index.js
- test/rewrite-request-headers.js
A new option allows to rewrite the request headers before sending them to the upstream server.
Closes #56
> Add `rewriteRequestHeaders` option

- index.js
- test/post-plain-text.js
As titled. This PR resolved issue #59.
I am not clear why the body needs to be stringified if it is `application/json`. Shouldn't it just be passed along to the remote host?
> Resolves issue #59

- .gitignore
- README.md
- index.d.ts
- index.js
- lib/request.js
- test/http-timeout.js
- test/http2-timeout.js
- test/types.test.ts
Addresses #68 
The general idea follows the discussion from the issue: introduce `http` & `http2` options, along with timeouts handling.
The new API:
```js
fastify.register(require('fastify-reply-from'), {
http: {
agentOptions: { // supports all options from https://nodejs.org/api/https.html#https_new_agent_options
keepAliveMsecs: 30000, // supersedes options.keepAliveMsecs
maxFreeSockets: 100, // supersedes options.maxFreeSockets
maxSockets: 200 // supersedes options.maxSockets
},
requestOptions : { // supports all options from https://nodejs.org/api/https.html#https_https_request_url_options_callback
timeout: 5000, // has default of 10000, with attached timeout callback
rejectUnauthorized: true // supersedes options.rejectUnauthorized, defaults to false (Node defaults to true)
}
}, …
```
> Introduce http & http2 options with timeouts

- README.md
- lib/request.js
- test/unix-http.js
- test/unix-https.js
This is not ready for merge as tests / documentation are needed, at this time I'm really just looking for feedback on the proposed API.  I can confirm `unix+http` works, I've used this branch to replace the `fastify-reply-from` used by `fastify-http-proxy`, the following is an example initialization:
```js
fastify.register(fastifyHttpProxy, {
upstream: `unix+http://${querystring.escape(runDir('http.sock'))}/`,
prefix: this.prefix
});
```
I got the idea of encoding the path as hostname from a [CURL thread](https://curl.haxx.se/mail/lib-2008-04/0280.html).  The separate `unix+http` protocol is easier to detect and should not impose a performance cost on TCP hostname based requests.  Also `unix+http` avoids potential ambiguity if someone uses a socket file in `cwd` such as …
> Add support for unix socket destination server

- index.js
- package.json
- test/http-invalid-target.js
- test/http2-invalid-target.js
- test/unexpected-error.js
Hi there.  Small change to add error handling for failed DNS lookup when using http 1.  There was an existing test for http 2 only.  Also changes the default error code when an unknown error occurs to 500 rather than 200.
> Handle ENOTFOUND error, set default error code to 500 rather than 200

- index.js
- test/http-invalid-target.js
- test/http2-invalid-target.js
- test/unexpected-error.js
Same as #87, but for 2.x branch
> Handle ENOTFOUND error, set default error code to 500 rather than 200 (2.x branch)

- index.js
- test/undici-timeout.js
> Support for UND_ERR_REQUEST_TIMEOUT

- README.md
- index.d.ts
- lib/request.js
- test/http-agents.js
- test/https-agents.js
- test/index.test-d.ts
Issue:
https://github.com/fastify/fastify-reply-from/issues/108 Add an option to provide custom http/s agent
- [ v] run `npm run test` and `npm run benchmark`
- [ v ] tests and/or benchmarks are included
- [ v ] documentation is changed or added
- [ v ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
> issue-108: Add an option to provide custom http/s agent

- README.md
> Fixes another typo in README.md

- .gitignore
- README.md
- index.js
- lib/utils.js
- test/build-url.js
As reported in https://github.com/fastify/fast-proxy/issues/42, this module too has similar vulnerability.
This PR fixes that.
> fix: sanitize source url to avoid attack

- index.js
- test/host-header.js
> fix: add port to host header if available

- lib/request.js
- test/core-with-path-in-base.js
- test/undici-with-path-in-base.js
This use case is relied upon by fast-proxy and it was working with
the Node.js core client but not with Undici.
> Support paths within base

- README.md
- index.js
- test/no-body-opts-with-head.js
**Changes:**
- updated docs
- changed error message to respect HTTP method
- added tests for no options.body, HEAD method
> fix: send correct error message when rewriting body fails (#150)

- README.md
- index.js
- package.json
- test/post-formbody.js
- test/post-with-custom-encoded-contenttype.js
This fixes https://github.com/fastify/fastify-reply-from/issues/117 which is caused by combining `fastify-reply-from` with `fastify-formbody` 
> fix: encoding when used with fastify-formbody plugin

- lib/request.js
- test/undici-options.js
Hi, I'm come from https://github.com/fastify/fastify-http-proxy/pull/163 😄 
undici's `strictContentLength` option is not working properly even after upgrading v6, so I dug into this.
I check the code from #179 and found it doesn't respect undici options at the moment of request(handleUndici). 
On requesting `handleUndici`, there's no `opts.undici` actually.
it should follow `undiciOpts` which set up on initialize of  `buildRequest`.
I also rewrote `test/undici-options` to check the options properly 
* for the initial time, on the `undici.Agent`'s constructor
* for the request time, on the `undici.Pool`'s constructor 
I hope this PR merges in and releasing a patch version. 🙏🏻 
> fix: undici options should apply on handleUndici

- README.md
- lib/request.js
- test/custom-undici-instance.js
> feat: add custom undici instance

- README.md
- index.d.ts
- index.js
- test/full-querystring-rewrite-option-function.js
Add a new option to allow queryString parameter to be a function.
> Support passing a function to the queryString option

- index.d.ts
- test/index.test-d.ts
Fixes #233 
One thing I am not so happy with is `retryMethods?: (HTTPMethods | "TRACE")[];`, but unfortunately `TRACE` [is not included](https://github.com/fastify/fastify/blob/main/types/utils.d.ts#L8) in `HTTPMethods`.
> Update type definitions

- README.md
- index.js
- test/full-rewrite-body-to-empty-string.js
- test/full-rewrite-body-to-null.js
- test/full-rewrite-body-to-undefined.js
Currently it is not possible to modify the proxied body to be undefined or an empty string since both of these values are falsy and the current implementation checks for the truthiness of `opts.body`.  This PR changes the behavior to check for the existence of `opts.body` instead (`"body" in opts`) to allow falsy values to be sent.
This would potentially be a breaking change since `fastify-reply-from` currently ignores the `body` param when it is set to `undefined` or an empty string.  The current empty string behavior feels unexpected, while the current behavior for `undefined` may be desired.  If that's the case, this could be reworked to have a more explicit way to strip the body, such as a new `doNotSendBody` option.
```
🌈 SUMMARY RESULTS 🌈
Suites:   72 passed, 72 of 72 completed …
```
> Allow empty body override

- README.md
- index.d.ts
- index.js
- test/disable-request-logging.js
- test/index.test-d.ts
added disableRequestLogging (optional) to fastify-reply-from  to disable request logging #232 
> feat(#232): added option disableRequestLogging to disable request logging

- index.d.ts
The documentation specifies here https://github.com/fastify/fastify-reply-from#http that the http props can be a boolean
This is confirmed by this line of code
https://github.com/fastify/fastify-reply-from/blob/5b16f63f6de321f6a5be16b9e89b74182d47092f/lib/request.js#L256
But not in the type definition
> fix: wrong FastifyReplyFromOptions.http type, could be boolean

- index.d.ts
Reverts fastify/fastify-reply-from#266
Imho the http can not be boolean. 
https://github.com/fastify/fastify-reply-from/blob/5b16f63f6de321f6a5be16b9e89b74182d47092f/lib/request.js#L256
The code itself just checks if it is an Object then assign it to httpOpts. If you assign anything else, than it will generate an empty Object. So basically, httpOpts is always an Object, no matter if you assign false or true to it.
> Revert "fix: wrong FastifyReplyFromOptions.http type, could be boolean"

- index.js
- package.json
> perf: replace querystring with fast-querystring

- README.md
If I read the code correctly than contentTypesToEncode is by default only application/json
https://github.com/fastify/fastify-reply-from/blob/d4949f4a9697d84186191000f4a5859d5ae3fecd/index.js#L25
So this PR corrects the docs.
> docs: set correct contentTypesToEncode in docs

- types/index.d.ts
- types/index.test-d.ts
Hi! :wave:
I noticed that `reply.from(…)`'s return type is `void`, while in reality it returns the `reply` (like most/all other plugins that decorate the `reply`).
I updated the type, and added a type check to one of the existing tests to verify the fix.
Do you think this looks reasonable?
and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md) **(I think – I'm not 100 % sure what exactly this entails)**
> fix: verify reply.from() return type

- lib/request.js
- lib/utils.js
- test/undici-chaining.js
Fixes #287 
Finally found the problem is caused by both `http` and `undici`.
1. `http` is not always treats the `header` to `latin1`.
https://github.com/nodejs/node/blob/2a29df64645a70bbb833298423a29206c4ec6a2e/lib/_http_outgoing.js#L361-L373
2. `undici` always perform `Buffer.from('').toString('utf8')` regardless the `header` encoding.
https://github.com/nodejs/undici/blob/2b260c997ad4efe4ed2064b264b4b546a59e7a67/lib/core/util.js#L216-L229
In combine of the above two problem.
The headers will parsed as a completely difference byte when chaining.
In this fix, we always treats the header as `latin1`. 
So, we are always consistence in the encoding.
> fix: undici headers

- lib/request.js
- lib/utils.js
- package.json
- Partial revert of 09cb8e75abc221091be5b2b2f75d371277fef76b (keep test case)
- Upgrade `undici@5.19.1` which include security patch
> Revert "fix: undici headers (#289)"

- README.md
- index.js
- test/get-upstream-type.js
- test/rewrite-headers-type.js
- test/rewrite-request-headers-type.js
- types/index.d.ts
- types/index.test-d.ts
Fixes #72, related to #168.
Currently, the options `rewriteHeaders`, `rewriteRequestHeaders`, and `getUpstream` are all sync-only.
The suggested workaround in #168 was to use hooks to decorate the request, however, only `onResponse` passes in the fastify request, the others passed in the raw request, rendering the decorations inaccessible.
This PR updates the methods above to use the fastify request as the parameter. The old parameter is still accessible at `request.raw`.
> Pass Fastify request to callbacks

- lib/request.js
- test/http-timeout.test.js
- test/http2-timeout.test.js
Related to #298. It was mentioned there `undici` possibly has a bug regarding this. I will work on creating a small reproduction and create an issue on that module
This checks the response headers for `content-type: text/event-stream`, and if found, get rid of any existing timeouts.
Fixes #298
> Disable http/http2 timeout for sse events

- lib/utils.js
- test/build-url.test.js
Fix:
- fastify/fastify-http-proxy#307
> fix proxying with double slash

- README.md
- index.js
- test/method.test.js
- types/index.d.ts
- types/index.test-d.ts
adds a `method` opt to overwrite the http method of the request that is being sent to the target. 
use case is that the target may only support a `POST` request, for example because it does not confirm to certain standards, but the proxy should expose the same endpoint as `PATCH`. with the `method` parameter set to `POST`, the incoming `PATCH` request is forwarded as `POST`.
> feat: add `method` opt to overwrite http method

- README.md
- index.js
- test/retry-with-a-custom-handler.test.js
- types/index.test-d.ts
Edit: ~~1. I have added `PATCH` and `POST` as given default `retryMethods`~~ see review by airhorns
2. I have added the option to pass a callback to handle retries in a custom fashion as defined by the client.
The motivation for this change is that out of the box `reply-from` does not retry 500's so gracefully handling such cases is not possible. As a result with this change you are able to write your own callback to retry 500's as you wish (or any other kind of error - using 500's here as an exemplar).
This can be done quite simply.
```
const customRetryLogic = (req, res, registerDefaultRetry, defaultRetryAfter) => {
if (res && res.statusCode === 500 && req.method === 'GET') {
return 300
}
return null
}
...
Fastify.reply(From, customRetry: { handler: customRetryLogic, retries: 10 }}
``` …
> [feature] custom retry callback

- README.md
- index.js
- test/retry-with-a-custom-handler.test.js
Initially the custom retry handler was put in place to give the client true freedom of handling retries. I quickly saw this comes at a cost of making the simple mistake (which I had done !) of infinitely retrying.
Now there are two approaches to this.
1) Respect the underlying spirit of custom retries and having the client handle the retries (which is what this PR is proposing by passing back the retriesCount).
2) Limiting it on the library and not the client level with a conditional.
I have no belief that one is greater than the other but would like to respect the spirit of the initial PR.
**_So whats the point of this PR at all._** To avoid hardcoding and passing values. This is simply cleaner.
> add: retriesCount property to the callback

- types/index.d.ts
- types/index.test-d.ts
Forgot to add the type definition for retriesCount added to the callback into my last PR. My mistake !
> add: (type definition) retriesCount

- index.js
- package.json
This brings `fastify-reply-from` in line with `fastify`, `fastify-cigtm` and `fastify-rate-limit`, by switching to toad-cache, which is faster than tiny-lry, and to a map-based (as opposed to object-based) cache, which is faster for string keys.
See [benchmark](https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/cache-get-inmemory-string/_results/results.md) results.
> build(deps): replace tiny-lru with toad-cache

- lib/request.js
- test/full-delete-http2.test.js
It appears that `DELETE` streams behave the same as `GET` streams in that they are not writable (immediately ended?), so calling `.end` on the stream throws a `write after end` error ([related issue](https://github.com/fastify/fastify-http-proxy/issues/253)).
I cannot find this documented anywhere in HTTP2 spec or in NodeJS HTTP2 module (aside from the `endStream` header, and `http2stream.endAfterHeaders` which don't seem to affect anything here - can anyone share insight?).
This PR simply adds the `DELETE` method to a check on whether or not to end the stream. The change fixes https://github.com/fastify/fastify-http-proxy/issues/253.
> fix: DELETE requests should not call stream.end

- README.md
- index.js
- test/full-querystring-rewrite-option-function-request.test.js
- types/index.d.ts
- types/index.test-d.ts
Pass the request to the queryString function in the same way that rewriteRequestHeaders has access to the request object.
Fixes: #364
> feat: pass request to the queryString function

- README.md
- index.js
- lib/request.js
- test/http2-timeout-disabled.test.js
> allow explicitly disabling request and session timeouts with 0
