fastify/fastify-reply-from

index.js, lib/request.js, test/http2-https.js, test/http2/full-post-http2.js, test/http2/http-http2.js, test/http2/http2-http2.js, test/http2/http2-invalid-target.js, test/http2/http2-target-crash.js, test/http2/http2-target-multi-crash.js, test/http2/http2.js
=> Fix crash when target server is unavailable

.travis.yml
=> Remove node 9 from build matrix

package.json
=> fix(package): update tiny-lru to version 4.0.2

package.json, test/http2/full-post-http2.js, test/http2/http-http2.js, test/http2/http2-invalid-target.js, test/http2/http2-target-crash.js, test/http2/http2-target-multi-crash.js
Fixes https://github.com/fastify/fastify-reply-from/issues/38
=> Fixed tests, added pump, updated deps

index.js, test/full-post-extended-content-type.js
Fixes: https://github.com/fastify/fastify-reply-from/issues/61
=> considering extended content-type header format

index.d.ts, package.json
=> Fix types for v3

index.js, test/get-with-body.js, test/head-with-body.js, test/undici-body.js
=> Support for latest undici and better spec compliance

lib/request.js, test/undici-body.js, test/undici.js
=> Remove connetion header

index.d.ts
Moved the current types of "from.options" into an exported interface FastifyReplyFromHooks
=> New interface FastifyReplyFromHooks

index.js, test/async-route-handler.js
=> support reply.from being returned from async route handler

lib/request.js, package.json
=> Updated to undici@2

README.md
=> Fix spelling of decorates

README.md
=> Document onResponse replacing reply body

.dependabot/config.yml, .github/dependabot.yml, .github/workflows/ci.yml
**Please excuse so many commits, was experimenting with automation**
- Upgraded dependabot config
- Added dependabot automerge action to the workflow
=> chore: create dependabot config

test/index.test-d.ts
Raised by CodeQL scan. The rest of the file uses semicolons so this should also.
=> style: make implicitly inserted semicolon explicit

.github/dependabot.yml, .github/workflows/ci.yml, README.md, package.json
=> chore: documentation and ci updates

index.js, lib/request.js, test/undici-timeout-body-partial.js, test/undici-timeout-body.js, test/undici-timeout.js
Address breaking changes introduced in undici@3
https://github.com/nodejs/undici/commit/9df73a1409769d25dab8d4d9dbeb8e11f0260763
*missing script: benchmark
=> Address breaking changes undici@2=>@3

README.md, index.js, lib/request.js, package.json, test/base-path.js, test/full-post-stream-core.js, test/full-rewrite-body-http.js, test/get-with-body.js, test/head-with-body.js, test/host-header.js, test/undici-options.js, test/unix-http-undici-from.js, test/unix-http-undici.js, test/unix-http.js, test/unix-https-undici.js, test/unix-https.js
=> Use undici by default

.github/workflows/ci.yml
=> ci: add windows-os to `matrix.os` array

.github/workflows/ci.yml
Bring style into line with other Fastify repos
=> style(ci): use standardized template

lib/utils.js, test/build-url.js
=> fix: handle default port in `base`

index.d.ts, test/index.test-d.ts
Add undici types definitions. I added only the Pool options, I hope I haven't missed something.
=> feat: add undici types definitions

index.js, test/onResponse.js
=> fix: onResponse request argument

README.md, index.d.ts, index.js, test/index.test-d.ts, test/rewrite-headers.js
=> Added request args to rewriteHeaders

index.d.ts, test/index.test-d.ts
Added contentTypesToEncode option definition for typescript
=> types: add `contentTypesToEncode` option

index.js
See https://github.com/fastify/fastify-plugin#name
=> chore(index): add plugin name to metadata

.npmrc, index.js, lib/errors.js, lib/request.js, package.json, test/http-invalid-target.js, test/http-timeout.js, test/http2-invalid-target.js, test/http2-target-crash.js, test/http2-target-multi-crash.js, test/http2-timeout.js, test/on-error.js, test/undici-timeout.js, test/unexpected-error.js
=> replace http-errors with @fastify/error

README.md, lib/request.js
=> fix readme regarding http option, make getHttpOpts resilient against null parameter

.github/workflows/ci.yml, .taprc, README.md, examples/example.js, package.json, types/index.d.ts, types/index.test-d.ts
=> move types to types folder, activate linting in pipeline, fix ci badge in readme 

lib/request.js, package.json
=> remove semver package and node version check

.taprc, index.js, lib/request.js, test/http2-invalid-base.js, test/http2-unix-socket.js, test/post-with-octet-stream.js, test/utils-filter-pseudo-headers.js
=> improve test coverage

README.md
=> doc: fix typo requestOptions

README.md, index.js, lib/request.js, package.json, test/http-global-agent.js, test/https-global-agent.js, test/undici-global-agent.js, types/index.d.ts, types/index.test-d.ts
=> feat(#284): added option globalAgent to make use of global agent

lib/request.js, test/http2-target-multi-crash.test.js, test/http2-timeout.test.js
Noticed in the readme it's stated the default timeout for http2 requests is 60 seconds, but in the code it's 6 seconds. If it was actually the readme that was incorrect, will be more than happy to fix it there instead
=> Fix default http2 timeout to be 60 seconds

test/core-with-path-in-base.test.js
=> fix ci pipeline

package.json, test/head-with-body.test.js
=> skip test on broken node 20.2.0

README.md, index.js, lib/request.js, test/undici-no-destroy.test.js, types/index.d.ts, types/index.test-d.ts
This PR adds an option to disable closing of the passed-in agent.
=> Add destroyAgent option

lib/request.js, package.json
=> Remove pump dependency

README.md, lib/request.js, package.json, test/undici-proxy-agent.test.js, types/index.d.ts, types/index.test-d.ts
=> feat: added option for undici proxy agent
